### ISSUE TITLE
Usuario logueado tiene error al estar iniciado

### ISSUE THREAD

**Issue by FMGordillo** [Partners-El-Bueno/Back#15]
![image](https://user-images.githubusercontent.com/7970174/68914393-28f89280-073d-11ea-9a45-3a09c9a816db.png)

**Comment by Tholem98** [comment]
Solucionado.

En la configuracion de auth0 hay que colocar la ruta exacta, un slash de más, un www que no va o un https en lugar de http, ocasionan este tipo de problemas
